name: xtripo
recipe: symfony
config:
  php: '8.3'
  xdebug: true
  webroot: htdocs/public
services:
  database:
    type: mysql:8.0
    creds:
      user: xtripo
      password: xtripo
      database: xtripo
  phpmyadmin:
    type: phpmyadmin
proxy:
    appserver:
        - 'xtripo.lndo.site'
    phpmyadmin:
        - 'phpmyadmin.xtripo.lndo.site'
tooling:
    composer:
        service: appserver
        cmd: composer
        dir: /app/htdocs
    console:
        service: appserver
        cmd: bin/console
        dir: /app/htdocs
    yarn:
        service: node
        dir: /app/htdocs
